package pipeline

import (
	"context"
	"fmt"
	"time"

	"github.com/yourorg/logai/internal/models"
)

// runGitLab executes stage 4: create a branch, commit the fix, and open an MR.
func (p *Processor) runGitLab(ctx context.Context, e models.Error, triage models.TriageResult, loc models.LocalizeResult, fix fixOutcome) error {
	jobID, err := p.startJob(ctx, e.ID, models.StageGitLab)
	if err != nil {
		return err
	}

	shortID := e.ID
	if len(shortID) > 8 {
		shortID = shortID[:8]
	}
	branchName := fmt.Sprintf("logai/%s-%d", shortID, time.Now().Unix())

	commitMessage := fmt.Sprintf("fix: AI-generated fix for %s %s error",
		triage.AffectedService, triage.RiskLevel)

	title := fmt.Sprintf("fix: [logai] %s — %s error in %s",
		triage.AffectedService, triage.RiskLevel, loc.FunctionName)

	description := fmt.Sprintf(`## AI-generated bug fix

**Error:** %s

**Risk level:** %s

**File:** %s:%d

**Fix confidence:** %s

### Reasoning
%s

### What changed
%s

---

⚠️ Auto-generated by logai. Review carefully before merging.`,
		e.Message, triage.RiskLevel, loc.FilePath, loc.LineNumber,
		fix.Confidence, loc.Reasoning, fix.FixSummary)

	// 1. Branch off the default branch.
	if err := p.GitLab.CreateBranch(ctx, branchName, p.Cfg.GitLabDefaultBranch); err != nil {
		p.failJob(ctx, jobID, err)
		return fmt.Errorf("gitlab: create branch: %w", err)
	}

	// 2. Commit the fixed file.
	if err := p.GitLab.CommitFile(ctx, branchName, loc.FilePath, fix.FixedCode, commitMessage); err != nil {
		p.failJob(ctx, jobID, err)
		return fmt.Errorf("gitlab: commit file: %w", err)
	}

	// 3. Open the MR (draft when human approval is required).
	isDraft := p.Cfg.HumanApprovalRequired
	mrURL, mrIID, err := p.GitLab.CreateMR(ctx, branchName, p.Cfg.GitLabMRTarget,
		title, description, isDraft, p.Cfg.GitLabMRAssigneeID)
	if err != nil {
		p.failJob(ctx, jobID, err)
		return fmt.Errorf("gitlab: create mr: %w", err)
	}

	// 4. Persist the MR.
	mr := models.MergeRequest{
		ID:         newID(),
		ErrorID:    e.ID,
		GitLabIID:  mrIID,
		GitLabURL:  mrURL,
		BranchName: branchName,
		IsDraft:    isDraft,
	}
	if err := p.DB.InsertMergeRequest(ctx, mr); err != nil {
		p.failJob(ctx, jobID, err)
		return fmt.Errorf("gitlab: save mr: %w", err)
	}

	if err := p.finishJob(ctx, jobID, mr); err != nil {
		return err
	}

	// 5. Mark the error fixed.
	if err := p.DB.UpdateErrorStatus(ctx, e.ID, models.StatusFixed); err != nil {
		return fmt.Errorf("gitlab: mark fixed: %w", err)
	}

	p.Logger.Info("gitlab done",
		"error_id", e.ID, "stage", models.StageGitLab,
		"branch", branchName, "mr_iid", mrIID, "mr_url", mrURL, "draft", isDraft)

	return nil
}
